/*

 PONGGAMEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Game_Boy_Dev_Tools\gbtd22\Tiles\PongBkgTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 41
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define ponggamemapWidth 20
#define ponggamemapHeight 18
#define ponggamemapBank 0

extern unsigned char ponggamemap[];

/* End of PONGGAMEMAP.H */
