/*

 PONGTITLESCREENMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Game_Boy_Dev_Tools\gbtd22\Tiles\PongFont_and_PongTitleScreen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define pongtitlescreenmapWidth 20
#define pongtitlescreenmapHeight 18
#define pongtitlescreenmapBank 0

extern unsigned char pongtitlescreenmap[];

/* End of PONGTITLESCREENMAP.H */
