/*

 PONGOPTIONSSCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Game_Boy_Dev_Tools\gbtd22\Tiles\PongFont.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define pongoptionsscreenWidth 20
#define pongoptionsscreenHeight 18
#define pongoptionsscreenBank 0

extern unsigned char pongoptionsscreen[];

/* End of PONGOPTIONSSCREEN.H */
