/*

 SPEEDPTITLESCREENMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Game_Boy_Dev_Tools\gbtd22\Tiles\SpeedPFont_and_SpeedPTitleScreen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define speedptitlescreenmapWidth 20
#define speedptitlescreenmapHeight 18
#define speedptitlescreenmapBank 0

extern unsigned char speedptitlescreenmap[];

/* End of SPEEDPTITLESCREENMAP.H */
