/*

 SPEEDPCUPMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 7 x 11
   Tile set      : C:\Game_Boy_Dev_Tools\gbtd22\Tiles\SpeedPCupTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 42
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define speedpcupmapWidth 7
#define speedpcupmapHeight 11
#define speedpcupmapBank 0

extern unsigned char speedpcupmap[];

/* End of SPEEDPCUPMAP.H */
