/*

 SPEEDPGAMEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Game_Boy_Dev_Tools\gbtd22\Tiles\SpeedPBkgTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 40
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define speedpgamemapWidth 20
#define speedpgamemapHeight 18
#define speedpgamemapBank 0

extern unsigned char speedpgamemap[];

/* End of SPEEDPGAMEMAP.H */
