/*

 SPEEDPTITLESCREENMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : F:\Projects\Game Boy Projects\Tiles_Maps_Assets\Tiles\SpeedPFont_and_SpeedPTitleScreen.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __speedptitlescreenmap_h_INCLUDE
#define __speedptitlescreenmap_h_INCLUDE

#define speedptitlescreenmapWidth 20
#define speedptitlescreenmapHeight 18
#define speedptitlescreenmapBank 0

extern const unsigned char speedptitlescreenmap[];

#endif

/* End of SPEEDPTITLESCREENMAP.H */
