/*

 SPEEDPOPTIONSSCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Game_Boy_Dev_Tools\gbtd22\Tiles\SpeedPFont.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define speedpoptionsscreenWidth 20
#define speedpoptionsscreenHeight 18
#define speedpoptionsscreenBank 0

extern unsigned char speedpoptionsscreen[];

/* End of SPEEDPOPTIONSSCREEN.H */
